micronaut:
  application:
    name: search
netty:
  default:
    allocator:
      max-order: 3
db:
  name: 'search'
  lemma-collection: 'lemmas'
  document-collection: 'documents'
  secret-collection: 'secrets'
