name: Java Format
on:
  push:
    branches:
    - main
    paths:
    - java/search/**

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          files: java/search/**/*.java

